spring:
  application:
    name: pica-employee
  zipkin:
    base-url: http://zipkin-server:9411/
server:
  port: 5002
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka